### ISSUE TITLE
poloniex margin support

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#279] opened 2020-11-22 08:35 UTC
Hello,
Here another crash

arbitrader_1  | 2020-11-22 00:02:10.463  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : ***** ENTRY *****
arbitrader_1  | 2020-11-22 00:02:10.876  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Entry spread: 0.00665887
arbitrader_1  | 2020-11-22 00:02:11.032  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exit spread target: -0.00684113
arbitrader_1  | 2020-11-22 00:02:11.170  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Long entry: Quoine XRP/USD 64.15465549 @ 0.46762 (0.00000 slip) = $30.0000000002338
arbitrader_1  | 2020-11-22 00:02:11.313  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Short entry: Poloniex XRP/USD 63.73028392 @ 0.47073382 (0E-8 slip) = $29.9999999993461744
arbitrader_1  | 2020-11-22 00:02:12.349  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Updated account balances: Quoine $104.74 + Poloniex $146.31 = $251.05
arbitrader_1  | 2020-11-22 00:02:13.760 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exchange returned an error executing trade!
arbitrader_1  |
arbitrader_1  | org.knowm.xchange.exceptions.ExchangeException: Not enough XRP.
arbitrader_1  |  at org.knowm.xchange.poloniex.PoloniexErrorAdapter.adaptBasedOnErrorMessage(PoloniexErrorAdapter.java:31)
arbitrader_1  |  at org.knowm.xchange.poloniex.PoloniexErrorAdapter.adapt(PoloniexErrorAdapter.java:19)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeService.placeLimitOrder(PoloniexTradeService.java:115)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.executeOrderPair(TradingService.java:781)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.entryPosition(TradingService.java:439)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.lambda$tick$5(TradingService.java:322)
arbitrader_1  |  at java.util.ArrayList.forEach(ArrayList.java:1259)
arbitrader_1  |  at com.r307.arbitrader.service.TradingService.tick(TradingService.java:301)
arbitrader_1  |  at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
arbitrader_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arbitrader_1  |  at java.lang.reflect.Method.invoke(Method.java:498)
arbitrader_1  |  at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
arbitrader_1  |  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
arbitrader_1  |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
arbitrader_1  |  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
arbitrader_1  |  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
arbitrader_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
arbitrader_1  |  at java.lang.Thread.run(Thread.java:748)
arbitrader_1  | Caused by: org.knowm.xchange.poloniex.dto.PoloniexException: Not enough XRP.
arbitrader_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
arbitrader_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
arbitrader_1  |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
arbitrader_1  |  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
arbitrader_1  |  at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call1(AnnotatedConstructor.java:129)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:326)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:147)
arbitrader_1  |  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
arbitrader_1  |  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
arbitrader_1  |  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
arbitrader_1  |  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
arbitrader_1  |  at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
arbitrader_1  |  at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
arbitrader_1  |  at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
arbitrader_1  |  at com.sun.proxy.$Proxy52.sell(Unknown Source)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.orderEntry(PoloniexTradeServiceRaw.java:150)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.sell(PoloniexTradeServiceRaw.java:115)
arbitrader_1  |  at org.knowm.xchange.poloniex.service.PoloniexTradeService.placeLimitOrder(PoloniexTradeService.java:101)
arbitrader_1  |  ... 17 common frames omitted
arbitrader_1  |
arbitrader_1  | 2020-11-22 00:02:14.305  WARN 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Polling exchanges took 4857 ms
arbitrader_1  | 2020-11-22 00:02:14.443 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exiting immediately to avoid erroneous trades.
arbitrader_arbitrader_1 exited with code 1

I have enough USD/USDC at both exchanges. 4 times over my fixedExposure to 30 USD

**Comment by sanitariu** [comment] 2020-11-22 08:38
Some thoughts ..... do we need to transfer USDC from exchange to margin account at poloniex ?
Your bot is reading balances but only from exchange ?

**Comment by sanitariu** [comment] 2020-11-22 13:06
I moved some USDC to poloniex margin but bot crashed again ... same reason.

{
    "longTrade": {
        "exchange": "Quoine",
        "orderId": null,
        "volume": 77.10949548,
        "entry": 0.4539
    },
    "shortTrade": {
        "exchange": "Poloniex",
        "orderId": null,
        "volume": 76.61542306,
        "entry": 0.45682708
    },
    "currencyPair": "XRP/USD",
    "exitTarget": -0.00705127,
    "entryBalance": 183.03,
    "entryTime": "2020-11-22T09:37:07.966Z"
}

The problem is that actually bot opened long position at liquid and i am minus there two times ....
I think bot should not crash but instead must try to open the short position at the other exchange.
If failure to do so its better to close all positions and send an email notification.
Opening long at one exchange and then crash without notice is just bad.

**Comment by scionaltera** [comment] 2020-11-23 05:12
In case of an error the bot will exit immediately which can (and often does) leave positions open. The reasoning for that is that there is no foolproof way to close all positions across all exchanges. A bug could cause an error on _closing_ a position just as easily as opening one. If the error handling code tried to reverse the mistake it could create more new incorrect orders and make the situation even worse. It could get into a loop trying to repeatedly close positions and instead adding more and more orders. I'd rather it just stop trying to do anything after it knows there is a problem and exit. Then the user can review the log and go into their accounts to get them back into a good state.

> Opening long at one exchange and then crash without notice is just bad.

It doesn't crash without notice. There's always at least a stack trace and if the exchange included any kind of message with the error that message will be included in the error output. I'll grant you that the program is not very user friendly for non-technical users yet, so you do need to be comfortable reading stack traces. Getting it to trade correctly has been, and will always be the priority.

> do we need to transfer USDC from exchange to margin account at poloniex ?

I'm not sure how margin trading works on Poloniex. I'm US based and when I was able to trade there they did not offer margin trading. Now I'm not allowed to trade there at all anymore. I think our community has the capability to investigate this further but I can't do it personally. As far as I am concerned margin trading on Poloniex using Arbitrader is an experimental feature at this time.

**Comment by scionaltera** [comment] 2020-11-26 07:25
In the past couple of days @dazito and I have observed a similar issue at Binance trying to trade margin. The issue there is that Binance has a completely separate API for margin trading and the XChange implementation only uses the spot trading API. In order to support margin on Binance we will need support for it in XChange. I will look into Poloniex to see if the problem there might be similar to that.

**Comment by scionaltera** [comment] 2020-12-20 07:42
Closing this because the problem is that XChange does not implement margin support for Poloniex. It's not something we can fix in Arbitrader.

**Closed by scionaltera** 2020-12-20 07:42 UTC
Labels: blocked, enhancement
